### ISSUE TITLE
Please add a separate license file

### ISSUE THREAD

**Issue by QuLogic** [lucasb-eyer/go-colorful#16]
I realize it's in the readme, but it's useful to have a separate license file for things like packaging, which can look directly at the file. It's also useful on GitHub since it can parse the file and [show that in its metadata](https://github.com/blog/2252-license-now-displayed-on-repository-overview).

**Comment by lucasb-eyer** [comment]
Fair point, done!

**Comment by QuLogic** [comment]
Thanks!
