### ISSUE TITLE
color.Color to colorful.Color conversion function

### ISSUE THREAD

**Issue by ZirconiumX** [lucasb-eyer/go-colorful#17]
I've been using go-colorful for a while in my own program [rbsmoke](https://github.com/ZirconiumX/rbsmoke), and in the name of being useful, I'm going to contribute my thoughts to this in a series of issues.

I've found I've needed to convert heavily between the Go stdlib's color.Color subtypes and colorful.Color a lot, and while I have [this snippet](https://github.com/ZirconiumX/rbsmoke/blob/master/colour.go#L18-L20) for my particular use, I don't think it's too far a stretch to imagine other colorspace conversions people may need.

**Comment by lucasb-eyer** [comment]
Thanks, your feedback is very welcome!

`colorful.Color` does implement the `color.Color` interface [here](https://github.com/lucasb-eyer/go-colorful/blob/master/colors.go#L14-L15), so I don't think `colorful.Color -> color.Color` is necessary, as it should be possible to drop `colorful.Color` anywhere that accepts a `color.Color`, right?

You linked to code for one specific `color.Color -> colorful.Color`, I agree that will be useful and missing it originally was an oversight! I have implemented a slightly more generic `MakeColorful` in #19.

Closing this issue as #19 solves it, but if I'm missing something, feel free to re-open!
