### ISSUE TITLE
More colour difference formulas

### ISSUE THREAD

**Issue by ZirconiumX** [lucasb-eyer/go-colorful#22]
Hello, it's me again.

I don't have an urgent need for performance this time, but I came across the [CIE Delta E* colour difference formulas](https://en.wikipedia.org/wiki/Color_difference#CIELAB_Delta_E*) which try to adjust for CIELAB being less perceptually uniform than planned, and thought they might be useful for people who want extreme accuracy.

**Comment by lucasb-eyer** [comment]
Hi, I'd happily accept a PR implementing this, but don't have the time (and need) to work on it myself currently.

Leaving this issue open for whomever wants to pick it up!

**Comment by lucasb-eyer** [comment]
Fixed by #30, thanks @rouhannb
