### ISSUE TITLE
semver releases for Go 1.11 Modules

### ISSUE THREAD

**Issue by mdouchement** [lucasb-eyer/go-colorful#31]
I'm using your helpful library in my project and I am facing to a [little problem](https://github.com/mdouchement/hdr/pull/18) because it seems `go mod` does not like tags that don't follow the semver semantic :(

https://github.com/golang/go/wiki/Modules
https://github.com/golang/go/wiki/Modules#semantic-import-versioning

**Comment by lucasb-eyer** [comment]
Done via #32, sorry for the long delay.
