### ISSUE TITLE
Remove dependency on DATA-DOG/go-sqlmock

### ISSUE THREAD

**Issue by benhoyt** [lucasb-eyer/go-colorful#38]
Hi @lucasb-eyer, thanks for this module! I'm using it indirectly via [gdamore/tcell](https://github.com/gdamore/tcell). I noticed this library depends on [DATA-DOG/go-sqlmock](https://github.com/DATA-DOG/go-sqlmock), but only for the runnable example in [hexcolor_test.go](https://github.com/lucasb-eyer/go-colorful/blob/b3ff143339304443cc5ee1c00995b51090f2c04d/hexcolor_test.go#L36).

I propose we remove the dependency on this unrelated library (it seems odd that a color library depends on a Datadog SQL mocking library). In addition to pulling an unnecessary dependency, it causes a lot of noise commits, eg: https://github.com/lucasb-eyer/go-colorful/commit/30298f24079860c4dee452fdef6519b362a4a026, https://github.com/lucasb-eyer/go-colorful/commit/4de7d682992e4105e105acd8ec5deb03a5bc542a, https://github.com/lucasb-eyer/go-colorful/commit/41bd1f4f1990ddbf36e4927bea4fa80173b33905, https://github.com/lucasb-eyer/go-colorful/commit/2341e02c5a001f748cbc6f3adc4a586e64365bd0.

Per your [comment](https://github.com/lucasb-eyer/go-colorful/pull/34#issuecomment-480541709) on April 6, it looks like you're not a big fan of it in any case:

> This is unfortunate, especially as sqlmock is only barely used for testing. I'm not up-to-date anymore and have to rely on PRs, so thanks a lot for fixing this!

Somebody else already created a [PR](https://github.com/lucasb-eyer/go-colorful/pull/36) to comment this code out, but I think we can do better than simply commenting it out and saying "this breaks everything". :-)

My suggestion is that we simply remove this example/test and get rid of the dependency (it's not even included in the [godoc output](https://godoc.org/github.com/lucasb-eyer/go-colorful#HexColor.Scan), though I'm not entirely sure why). You have an example of usage in the README [here](https://github.com/lucasb-eyer/go-colorful#reading-and-writing-colors-from-databases), so I don't think it'll make it any harder to figure out.

I'm happy to whip up a PR removing this and tidying up the dependencies. Thoughts?

**Comment by lucasb-eyer** [comment]
Yup, your proposal sounds good to me and I'll happily accept a PR!

**Comment by diamondburned** [comment]
+1

I also broke my PR, so I agree.

**Comment by benhoyt** [comment]
Done in https://github.com/lucasb-eyer/go-colorful/pull/39

**Comment by lucasb-eyer** [comment]
Thanks all!

**Comment by benhoyt** [comment]
Thank you @lucasb-eyer! Do you mind tagging a new release `v1.0.3` with this included, so that modules that depend on this can start benefiting?

**Comment by lucasb-eyer** [comment]
Thanks for reminding me, done. And let me know if I still missed something else :)

**Comment by benhoyt** [comment]
Thanks!
