### ISSUE TITLE
doc: DistanceCIE76 underdocumented

### ISSUE THREAD

**Issue by dolmen** [lucasb-eyer/go-colorful#40]
The [documentation for DistanceCIE76](https://pkg.go.dev/github.com/lucasb-eyer/go-colorful?tab=doc#Color.DistanceCIE76) says:
> That's actually the same, but I don't want to break code.

Same as what?

**Comment by ErnestoBorio** [comment]
As you can see in the code, it's the same that the function immediately before:
https://github.com/lucasb-eyer/go-colorful/blob/v1.0.3/colors.go#L593

**Comment by dolmen** [comment]
My point is that should be written in the doc itself.

**Comment by KelSolaar** [comment]
Looking at the doc:

> // DistanceLab is a good measure of visual similarity between two colors!

This is not quite true, simple Euclidean distance in CIE Lab space IS NOT a good measure because perceptual uniformity of CIE Lab is not great. It the main reason why the CIE introduced the CIE 1994 and CIE 2000 quasi-metrics.

**Comment by makeworld-the-better-one** [comment]
@dolmen This is properly documented now.

@KelSolaar What would you suggest be written fro `DistanceLab` instead?
