### ISSUE TITLE
Support for HSLuv

### ISSUE THREAD

**Issue by muesli** [lucasb-eyer/go-colorful#41]
See: https://www.kuon.ch/post/2020-03-08-hsluv/

**Comment by makeworld-the-better-one** [comment]
The official HSLuv website is [here](https://www.hsluv.org/).

Converting to HSLuv is already implemented in Go at [github.com/hsluv/hsluv-go](https://github.com/hsluv/hsluv-go). Of course it would still be nice to have this implemented here. That library even uses RGB values between 0 and 1 already, so the code could just be copied for the most part.

**Comment by makeworld-the-better-one** [comment]
The README mentions

> While this seems all good, you need to know one thing: When interpolating in any of the CIE color spaces, you might get invalid RGB colors!

HSLuv fixes this, see [here])(https://hsluv.org/comparison/).

**Comment by makeworld-the-better-one** [comment]
I have added HSLuv support in #51.

cc @muesli

**Comment by muesli** [comment]
Nice one!
