### ISSUE TITLE
very large json file in the middle of the package.

### ISSUE THREAD

**Issue by hazarek** [lucasb-eyer/go-colorful#58]
this json file size is too large. What does it do? 1.5mb. It unnecessarily inflates the packet size. Can i delete it from my vendor folder? (`go mod vendor`)
https://github.com/lucasb-eyer/go-colorful/blob/master/hsluv-snapshot-rev4.json

**Comment by makeworld-the-better-one** [comment]
It is used for testing this package and ensuring its accuracy. It never makes its way into any final binary. You can safely delete it, as it is only used when testing this package during development.

**Comment by hazarek** [comment]
thanks for information
