### ISSUE TITLE
Documentation of CIE LCh(uv)

### ISSUE THREAD

**Issue by yurivish** [lucasb-eyer/go-colorful#59]
Hi, thanks for this great package. I'm using it to convert colors to `LuvLCh`, and noticed that whi

The documentation says

> This is generally the most useful one; CIE-L*a*b* space in polar coordinates, i.e. a better HSV. H° is in [0..360], C* almost in [-1..1] and L* as in CIE-L*a*b*.

But I noticed that C* is in [0..1]; this makes sense, since the hue is 0-360, rather than 0-180.

I might be misunderstanding something, but it seems the documentation could be updated to reflect the narrowed range of the C* parameter, and this might apply to the other similar color spaces too.

Thanks again!

**Comment by makeworld-the-better-one** [comment]
I can confirm that C is always >= 0. Thanks for making this issue. Fixed in 614c0f3.
