### ISSUE TITLE
HSV hue range?

### ISSUE THREAD

**Issue by quillaja** [lucasb-eyer/go-colorful#71]
Maybe I'm doing something wrong, but I expected
```go
c := colorful.Hsv(360, 1, 1)
```
to be red (RGB 255,0,0) but get black (RGB 0,0,0).
With hue = 359.9, the color is red as expected.
Documentation says H is in [0, 360] not [0, 360).

Possibly `colors.go` line 188:
```go
	case 5.0 <= Hp && Hp < 6.0:
		r = C
		b = X
	}
```
360/60 = 6, which is covered by no case. Variables `r`, `g`, `b` default to 0, and since `S` and `V` are 1, `m` is also 0.

**Comment by makew0rld** [comment]
I fixed the docs in a472fc29eb4b to explain that 360 isn't allowed. This makes sense as 0deg=360deg. If you'd like to change the code to improve handling of this I would look at a PR. Thanks!
