### ISSUE TITLE
rand.Seed is deprecated

### ISSUE THREAD

**Issue by lublak** [lucasb-eyer/go-colorful#72]
currently we can use

```go
rand.Seed(seed)
```

to set an seed for a HappyPalette.
Go says:

```
rand.Seed is deprecated ...... should use New(NewSource(seed))
```

At the moment it doesn't matter as long as there is still the possibility.
I think something like that would be practical:

```go
colorful.FastHappyPalette(3)
// with custom seed:
colorful.FastHappyPaletteWithRand(3, rand.New(rand.NewSource(seed)))
```

**Comment by makew0rld** [comment]
Fair enough. I would accept a PR for this.

**Comment by lublak** [comment]
@makew0rld i created a pull request for this: #73
