### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by muhqu** [lucasb-eyer/go-colorful#8]
I want to use [Sourcegraph](https://sourcegraph.com) for go-colorful code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/lucasb-eyer/go-colorful. (It should only take 30 seconds.)

Thank you!

**Comment by lucasb-eyer** [comment]
[Amidoinitrite?](https://sourcegraph.com/github.com/lucasb-eyer/go-colorful) I didn't know about this at all, so if some things need change for better browsability, let me know or better yet PR.

**Comment by muhqu** [comment]
All fine, thanks a :bouquet: ! … as you're into [go ![](http://golang.org/favicon.ico)](http://golang.org), you should definitely follow Sourcegraph's excellent [Blog](https://sourcegraph.com/blog)! …and/or follow @sqs
